#!/bin/bash
# Script 5: Open Source Manifesto Generator
# Author: Abhijit Tripathi | Reg: 24BCE10548

# Alias concept: 'alias today="date +%d\ %B\ %Y"' could be added to ~/.bashrc
# In this script we use the full command for portability.

echo "================================================"
echo " Open Source Manifesto Generator"
echo " Abhijit Tripathi | 24BCE10548"
echo "================================================"
echo ""
echo "Answer three questions to generate your manifesto."
echo ""

# Interactive user input using read
read -p "1. Name one open-source tool you use every day: " TOOL
read -p "2. In one word, what does 'freedom' mean to you? " FREEDOM
read -p "3. Name one thing you would build and share freely: " BUILD

DATE=$(date '+%d %B %Y')
OUTPUT="manifesto_$(whoami).txt"

# Write manifesto using string concatenation and >>
echo "Open Source Manifesto" > "$OUTPUT"
echo "Generated by: $(whoami) on $DATE" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "Every day, I rely on $TOOL — a tool built not for profit" >> "$OUTPUT"
echo "but for the shared progress of everyone who uses it." >> "$OUTPUT"
echo "To me, freedom means $FREEDOM: the right to see," >> "$OUTPUT"
echo "modify, share, and improve the tools that shape our lives." >> "$OUTPUT"
echo "If I build something that works, I will share it freely —" >> "$OUTPUT"
echo "starting with $BUILD." >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "Signed: $(whoami) | $(date '+%d %B %Y')" >> "$OUTPUT"

echo ""
echo "Manifesto saved to $OUTPUT"
echo "--- Your Manifesto ---"
cat "$OUTPUT"
